version: '3'

services:
  master:
    image: ros:melodic-ros-core
    container_name: master
    command: roscore

  dev:
    build: .
    container_name: dev
    environment:
        - "ROS_HOSTNAME=dev"
        - "ROS_MASTER_URI=http://master:11311"
    command: tail -f /dev/null
    volumes:
        - ./catkin_ws:/root/catkin_ws
    depends_on:
        - master

  talker:
    image: ros:melodic-ros-core
    container_name: talker
    environment:
        - "ROS_MASTER_URI=http://master:11311"
        - "ROS_HOSTNAME=talker"
    command: ./root/catkin_ws/src/beginner_tutorials/scripts/start_talker.sh
    volumes:
        - ./catkin_ws:/root/catkin_ws
    depends_on:
        - master

  listener:
    image: ros:melodic-ros-core
    container_name: listener
    environment:
        - "ROS_MASTER_URI=http://master:11311"
        - "ROS_HOSTNAME=listener"
    command: ./root/catkin_ws/src/beginner_tutorials/scripts/start_listener.sh
    volumes:
        - ./catkin_ws:/root/catkin_ws
    depends_on:
        - master

networks:
  default:
    external:
      name: skynet